name: Fabricar Inyector EXE

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargar el codigo fuente
      uses: actions/checkout@v4

    - name: Configurar MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Compilar el Inyector
      run: |
        $slnFile = Get-ChildItem -Path . -Filter *.sln* -Recurse | Select-Object -First 1
        msbuild $slnFile.FullName /p:Configuration=Release /p:Platform=x64

    - name: Entregar el archivo final
      uses: actions/upload-artifact@v4
      with:
        name: Inyector-Debian
        path: "**/x64/Release/*.exe"
